# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongid the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


User.create({username: "mcooper0", password: "AJMRvD7bsGeC"})
User.create({username: "clawson1", password: "qpTHu8TSQ"})
User.create({username: "kwhite2", password: "Rz5qHXH9RvEJ"})
User.create({username: "mkennedy3", password: "WoySQN"})
User.create({username: "kmoore4", password: "IqVES9c0s"})
User.create({username: "wbennett5", password: "52fAGaPjBPr"})
User.create({username: "jhansen6", password: "dTye8S5KNy"})
User.create({username: "mrodriguez7", password: "76aHf23L"})
User.create({username: "kwalker8", password: "V8DpIo0TH"})
User.create({ username: "jdiaz9", password: "cgin7N5Ujo"})
User.create({ username: "aandersona", password: "HVcJq2v"})
User.create({ username: "cmontgomeryb", password: "IwYFxhdUK80"})
User.create({ username: "ahayesc", password: "OOHjZySqGb8"})
User.create({ username: "dstephensd", password: "LJoIvOZ"})
User.create({ username: "cgarciae", password: "ap73kdcBBwxN"})
User.create({ username: "klawrencef", password: "921Ccu"})
User.create({ username: "agilbertg", password: "zu2WhaiLK8"})
User.create({ username: "cwillish", password: "Cmayra6"})
User.create({ username: "mdanielsi", password: "Apal3W"})
User.create({ username: "wrosej", password: "kEBYKDf2dM"})
User.create({ username: "amccoyk", password: "of0LcXcPw4"})
User.create({ username: "pwilliamsonl", password: "h2nmG9P"})
User.create({ username: "jwarrenm", password: "SLqXrCrtCT7E"})
User.create({ username: "ekennedyn", password: "0QR1B05BcWmj"})
User.create({ username: "ehanseno", password: "QBN73b"})
User.create({ username: "kmendozap", password: "3UclsjQUbFz"})
User.create({ username: "nrogersq", password: "OQnJIW1UTgw"})
User.create({ username: "jhamiltonr", password: "IGnEJUnfuT"})
User.create({ username: "tbrookss", password: "QTvBx6fBr"})
User.create({ username: "lfishert", password: "e31AWc"})
User.create({ username: "lhansonu", password: "wg7N9YtjZr"})
User.create({ username: "bwilliamsonv", password: "Z8LNEL277WJ"})
User.create({ username: "tcollinsw", password: "3YDFHSt"})
User.create({ username: "gpattersonx", password: "1RmSDcfLqhlV"})
User.create({ username: "djohnstony", password: "py5IgYjEIAuU"})
User.create({ username: "kpowellz", password: "tCFjZAQq"})
User.create({ username: "dfranklin10", password: "3iEqU30GdU"})
User.create({ username: "lhayes11", password: "guPBndCt"})
User.create({ username: "lrichards12", password: "x4oGqjF"})
User.create({ username: "jday13", password: "EqlFbK"})
User.create({ username: "guest", password: "guest123"})
