# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongid the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


User.create({id: 1, username: "mcooper0", password: "AJMRvD7bsGeC"})
User.create({id: 2, username: "clawson1", password: "qpTHu8TSQ"})
User.create({id: 3, username: "kwhite2", password: "Rz5qHXH9RvEJ"})
User.create({id: 4, username: "mkennedy3", password: "WoySQN"})
User.create({id: 5, username: "kmoore4", password: "IqVES9c0s"})
User.create({id: 6, username: "wbennett5", password: "52fAGaPjBPr"})
User.create({id: 7, username: "jhansen6", password: "dTye8S5KNy"})
User.create({id: 8, username: "mrodriguez7", password: "76aHf23L"})
User.create({id: 9, username: "kwalker8", password: "V8DpIo0TH"})
User.create({id: 10, username: "jdiaz9", password: "cgin7N5Ujo"})
User.create({id: 11, username: "aandersona", password: "HVcJq2v"})
User.create({id: 12, username: "cmontgomeryb", password: "IwYFxhdUK80"})
User.create({id: 13, username: "ahayesc", password: "OOHjZySqGb8"})
User.create({id: 14, username: "dstephensd", password: "LJoIvOZ"})
User.create({id: 15, username: "cgarciae", password: "ap73kdcBBwxN"})
User.create({id: 16, username: "klawrencef", password: "921Ccu"})
User.create({id: 17, username: "agilbertg", password: "zu2WhaiLK8"})
User.create({id: 18, username: "cwillish", password: "Cmayra6"})
User.create({id: 19, username: "mdanielsi", password: "Apal3W"})
User.create({id: 20, username: "wrosej", password: "kEBYKDf2dM"})
User.create({id: 21, username: "amccoyk", password: "of0LcXcPw4"})
User.create({id: 22, username: "pwilliamsonl", password: "h2nmG9P"})
User.create({id: 23, username: "jwarrenm", password: "SLqXrCrtCT7E"})
User.create({id: 24, username: "ekennedyn", password: "0QR1B05BcWmj"})
User.create({id: 25, username: "ehanseno", password: "QBN73b"})
User.create({id: 26, username: "kmendozap", password: "3UclsjQUbFz"})
User.create({id: 27, username: "nrogersq", password: "OQnJIW1UTgw"})
User.create({id: 28, username: "jhamiltonr", password: "IGnEJUnfuT"})
User.create({id: 29, username: "tbrookss", password: "QTvBx6fBr"})
User.create({id: 30, username: "lfishert", password: "e31AWc"})
User.create({id: 31, username: "lhansonu", password: "wg7N9YtjZr"})
User.create({id: 32, username: "bwilliamsonv", password: "Z8LNEL277WJ"})
User.create({id: 33, username: "tcollinsw", password: "3YDFHSt"})
User.create({id: 34, username: "gpattersonx", password: "1RmSDcfLqhlV"})
User.create({id: 35, username: "djohnstony", password: "py5IgYjEIAuU"})
User.create({id: 36, username: "kpowellz", password: "tCFjZAQq"})
User.create({id: 37, username: "dfranklin10", password: "3iEqU30GdU"})
User.create({id: 38, username: "lhayes11", password: "guPBndCt"})
User.create({id: 39, username: "lrichards12", password: "x4oGqjF"})
User.create({id: 40, username: "jday13", password: "EqlFbK"})
User.create({id: 41, username: "guest", password: "guest123"})
